### ISSUE TITLE
Stuck on splashscreen when not in debug

### ISSUE THREAD

**Issue by QuentinSc** [loicgeek/todo_getx#3]
Hello and thank you for this very good architecture example with Get.
I found a problem and can't fix it.
Flutter 1.17.5 / Android Q
1. Run the app with your ide (so in debug and attached to a device, real or emulator)
2. Stop the debugger
3. Make sure the app is closed on the device
4. Launch the app directly from the device
You get stuck on the splashscreen. No redirection on login or homepage..
Don't know if it's the same with a release build.

Sorry for my english, hope somebody can find a solution ! 

thank you

**Comment by loicgeek** [comment]
@QuentinSc  happy you liked the architecture. Actually, you are running neither in release nor in debug mode. If you want to run in release run `flutter build apk --release` , locate your build folder and install it on your phone. when you stop from debugging sessions there is too much trash that don't let the app start properly. And lol, don't worry about your English even me m not a native English speaker.

**Comment by QuentinSc** [comment]
@loicgeek Thank you for the answer!
It's the first time I see an app that dont run correctly after debugging session, (even with storage and cache file cleaned). You know exactly what causing that ? (for my education ^^)

**Comment by loicgeek** [comment]
@QuentinSc  I don't exactly know what caused that.

**Comment by loicgeek** [comment]
As it is solved m gonna close this issue.
