### ISSUE TITLE
issue in handleSignIn function in auth.controller.dart

### ISSUE THREAD

**Issue by SatyamKr07** [loicgeek/todo_getx#6]
After logout, press back button. Open app again , you get this error:
E/flutter ( 2454): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'pushNamedAndRemoveUntil' was called on null.
E/flutter ( 2454): Receiver: null
E/flutter ( 2454): Tried calling: pushNamedAndRemoveUntil<dynamic>("/login", Closure: (Route<dynamic>) => bool, arguments: null)

This point to handleSignIn function, ( Get.toNamed ) throws the error and we get stuck in splash screen.

**Comment by loicgeek** [comment]
> After logout, press back button. Open app again , you get this error:
> E/flutter ( 2454): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'pushNamedAndRemoveUntil' was called on null.
> E/flutter ( 2454): Receiver: null
> E/flutter ( 2454): Tried calling: pushNamedAndRemoveUntil("/login", Closure: (Route) => bool, arguments: null)
> 
> This point to handleSignIn function, ( Get.toNamed ) throws the error and we get stuck in splash screen.

Hi @SatyamKr07 ,please refer to this link https://github.com/jonataslaw/getx/issues/364

**Comment by loicgeek** [comment]
I have already fixed it
